services:
  web:
    container_name: bayit-backend
    build: .
    ports:
      - "8129:5000"
    environment:
      - FIREBASE_SERVICE_ACCOUNT_PATH=/app/serviceAccountKey.json
      - MONGODB_URI=mongodb://rootn0security:rootn0securitymongodb@bayit-mongo:27017/bayit?authSource=admin
      - MONGODB_DB=bayit
    volumes:
      # מיפוי התיקייה הנוכחית לתוך /app כדי ש-git pull ישפיע על הקבצים
      - .:/app
      - ../zenlist_databases:/app/databases
      - ../zenlist_receipts:/app/receipts
      - ../zenlist_original_receipts_backup:/app/original_receipts_backup
      - ./serviceAccountKey.json:/app/serviceAccountKey.json:ro
    # הפקודה המאוחדת: עדכון ואז הרצה
    command: >
      sh -c "git config --global --add safe.directory /app && git pull && python app.py"
    restart: always
    networks:
      - bayit-network


networks:
  bayit-network:
    external: true